// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ixouzzibkwralpjlabjm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml4b3V6emlia3dyYWxwamxhYmptIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0OTM2NDUsImV4cCI6MjA3MDA2OTY0NX0.5q9jn6X8Vpz0O9Fm67GP7875qnOV_yV92QgOBuJai-4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});